version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev
    volumes:
      - ./plugins/netzbegruenung.sms-authenticator-v26.0.6.jar:/opt/keycloak/providers/netzbegruenung.sms-authenticator-v26.0.6.jar
      - ./plugins/keycloak-2fa-email-authenticator-v1-KC26.0.7.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-v1-KC26.0.7.jar
      - ./plugins/email:/opt/keycloak/themes/base/email
    environment:
      KC_HEALTH_ENABLED: true
      KC_HTTP_ENABLED: true
      KEYCLOAK_ENABLE_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
      KC_FEATURES: preview
      # Admin Configuration
      # KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      # KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # DB Configuration
      # KC_DB: postgres
      # KC_DB_URL: jdbc:postgresql://postgres/${PG_DB}
      # KC_DB_USERNAME: ${PG_USER}
      # KC_DB_PASSWORD: ${PG_PASSWORD}
      # KC_DB_SCHEMA: public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge